openapi: 3.0.1
info:
  title: API Pipeline Demo (AspNetCore)
  description: ' This API version has been deprecated.'
  version: "2.0"
  contact:
    email: support@appyway.com
    url: https://appyway.com/get-in-touch-support/
    name: AppyWay Support
servers:
- url: https://api.appyway.com/v2/ApiPipelineDemoAspNetCore
paths:
  /Orders:
    post:
      tags:
      - Orders
      summary: Places a new order.
      description: Places a new order.
      operationId: post-orders
      requestBody:
        description: The order to place.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          text/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "201":
          description: The order was successfully placed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        "400":
          description: The order is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
  /Orders/{id}:
    get:
      tags:
      - Orders
      summary: Gets a single order.
      description: Gets a single order.
      operationId: get-orders-id
      parameters:
      - name: id
        in: path
        description: Format - int32. The requested order identifier.
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: The order was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        "404":
          description: The order does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
  /People/{id}:
    get:
      tags:
      - People
      summary: Gets a single person.
      description: Gets a single person.
      operationId: get-people-id
      parameters:
      - name: id
        in: path
        description: Format - int32. The requested person identifier.
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: The person was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "404":
          description: The person does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
components:
  schemas:
    Order:
      required:
      - customer
      type: object
      properties:
        customer:
          type: string
          description: Gets or sets the name of the ordering customer.
        createdDate:
          type: string
          description: Gets or sets the date and time when the order was created.
          format: date-time
        id:
          type: integer
          description: Gets or sets the unique identifier for the order.
          format: int32
      additionalProperties: false
      description: Represents an order.
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    Person:
      required:
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          maxLength: 25
          minLength: 0
          type: string
          description: Gets or sets the first name of a person.
        lastName:
          maxLength: 25
          minLength: 0
          type: string
          description: Gets or sets the last name of a person.
        id:
          type: integer
          description: Gets or sets the unique identifier for a person.
          format: int32
      additionalProperties: false
      description: Represents a person.
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
  responses:
    TooManyRequests:
      description: Too many requests
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
tags:
- name: Orders
  description: Represents a RESTful service of orders.
- name: People
  description: Represents a RESTful people service.
security:
- apiKey: []
- oAuth2: []

